DROP TABLE IF EXISTS micro_data; 

CREATE TABLE IF NOT EXISTS micro_data (
    source_study TEXT NOT NULL,
    accession TEXT NOT NULL UNIQUE,
    alias TEXT NOT NULL,
    center_name TEXT NOT NULL,
    broker_name TEXT,
    title TEXT NOT NULL, 
    taxon_id TEXT NOT NULL,
    scientific_name TEXT NOT NULL,
    common_name TEXT,
    description TEXT,
    bio_material TEXT,
    culture_collection TEXT,
    specimen_voucher TEXT,
    collected_by TEXT,
    collection_date TEXT,
    country TEXT,
    host TEXT,
    identified_by TEXT,
    isolation_source TEXT,
    lat_lon TEXT,
    lab_host TEXT,
    environmental_sample TEXT,
    mating_type TEXT,
    sex TEXT,
    cell_type TEXT,
    dev_stage TEXT,
    tissue_type TEXT,
    cultivar TEXT,
    ecotype TEXT,
    isolate TEXT,
    strain TEXT,
    sub_species TEXT,
    cell_line TEXT,
    serotype TEXT,
    serovar TEXT,
    custom_attributes TEXT NOT NULL,
    disease TEXT,
    is_control TEXT,
    is_tumor TEXT,
    classification_evidence TEXT,
    tier TEXT, 
    review_reason TEXT,
    year_reviewed TEXT,
    journal TEXT,
    n_samples TEXT, 
    repository_link TEXT, 
    paper_link TEXT,
    disease_evidence TEXT,
    disease_present	TEXT,
    disease_from_names TEXT, 
    age_present	TEXT, 
    sex_present	TEXT, 
    antibiotic_present TEXT,
    geography_present TEXT,
    body_site_group	TEXT, 
    sequencing_type TEXT, 
    disease_group TEXT,
    age_key	TEXT,
    sex_key	TEXT, 
    disease_key	TEXT,
    reviewer TEXT,
    reviewer_agrees	TEXT, 
    reviewer_notes TEXT
);