CREATE TABLE if not exists data(
    id INTEGER NOT NULL AUTO_INCREMENT,
    source_study VARCHAR(20) NOT NULL UNIQUE,
    accession VARCHAR(20) NOT NULL,
    alias TEXT NOT NULL,
    center_name TEXT NOT NULL,
    broker_name TEXT NOT NULL,
    title TEXT NOT NULL,
    taxon_id INT(8) NOT NULL
    scientific_name TEXT NOT NULL,
    common_name TEXT,
    description TEXT,
    bio_material TEXT,
    culture_collection TEXT,
    specimen_voucher TEXT,
    collected_by TEXT NOT NULL, 
    collection_date TEXT, 
    country TEXT, 
    host TEXT NOT NULL, 
    identified_by TEXT,
    isolation_source TEXT, 
    lat_lon POINT NOT NULL, 
    lab_host TEXT, 
    environmental_sample
    mating_type TEXT,
    sex TEXT,
    cell_type TEXT, 
    dev_stage TEXT, 
    tissue_type TEXT, 
    cultivar TEXT, 
    ecotype TEXT, 
    isolate TEXT, 
    strain TEXT, 
    sub_species TEXT, 
    cell_line TEXT, 
    serotype TEXT, 
    serovar TEXT, 
    custom_attributes TEXT, 
    PRIMARY KEY(id);
);